services:
  - type: web
    name: sml25-backend
    runtime: python
    rootDir: .
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    plan: free
    healthCheckPath: /health
    envVars:
      - key: SENDER_EMAIL
        sync: false
      - key: SENDER_PASSWORD  
        sync: false
      - key: RECIPIENT_EMAIL
        sync: false
    autoDeploy: true